//
// Created by manoyuria on 2015/6/18.
//

#ifndef SEQTRUAN_THEME_H
#define SEQTRUAN_THEME_H

#endif //SEQTRUAN_THEME_H
#define TIMELINE_HEIGHT  280
#define TIMELINE_TRACK_PANEL_DEF_WIDTH  300
#define TIMELINE_CURSOR_EDGE_COL 0xd41616
#define TIMELINE_TRACK_FRAME_MAX_WIDTH 40
#define TIMELINE_TRACK_DEF_HEIGHT 80
#define TIMELINE_COL_BG 0x484848
